### PR TITLE
Fix opportunity fixture

### LINKED ISSUE #348: Corrigir as fixtures de Oportunidades
## WHAT

Atualizar a fixture de oportunidades para garantir que a coluna type seja preenchida corretamente, evitando que a coluna fique com valores nulos. Isso permitirá que o mapa funcione normalmente e que todas as oportunidades disponíveis possam ser acessados e listadas.

## ADDITIONAL INFO

- [x] Verificar o arquivo da fixture de oportunidades.
- [x] Certificar-se de que as oportunidades estão sendo listadas na tela de oportunidades.

## COMO ESTÁ ATUALMENTE:

A tela de oportunidades não está listando os resultados
Image

O problema está nesse campo que não deveria ser nulo
Image

### PR DESCRIPTION
**Pull request by henriquelopeslima**
| Q             | A                                                                                                                         |
|---------------|---------------------------------------------------------------------------------------------------------------------------|
| Branch?       | fix/opportunity-fixture |
| Bug fix?      | yes  |
| New feature? | no |
| Deprecations? | no  |
| Issues        | Fix #348 |

### CODE REVIEW

**Review by saracamilo — APPROVED** [review]

**Comment by henriquelopeslima** [comment]
image

**Review by TalysonSoares — APPROVED** [review]

**Review by alessandrofeitoza — APPROVED** [review]

File: app/src/DataFixtures/OpportunityFixtures.php [hunk 1]
```diff
@@ -33,6 +33,7 @@ class OpportunityFixtures extends Fixture implements DependentFixtureInterface
                 'Artes',
                 'Teste',
             ],
+            'type' => 23,
```
Comment (alessandrofeitoza) [inline app/src/DataFixtures/OpportunityFixtures.php:36]: porque 23 @henriquelopeslima ?

Comment (henriquelopeslima) [reply app/src/DataFixtures/OpportunityFixtures.php:36]: Só para mudar o type mesmo.
image
